Repository Song-Daeun/VR_SONA, pull requests merged in 2025-05, with the labels that each got.

#16 [Fix] UserSettings 폴더를 Git이 추적하지 않도록 .gitignore 경로 수정
  .gitignore
Labels: :hammer_and_wrench:fix

#28 [Style] terrain 및 tile 스케일 조정
  VR_SONA/Assets/Scenes/UIScene.unity
  VR_SONA/Assets/UI/Terrain/New Terrain.asset
Labels: :face_exhaling:style

#31 [Fix] 타이머바와 코인 UI를 HMD 화면 기준으로 고정 및 위치 재배치
  VR_SONA/Assets/Scenes/UIScene.unity
  VR_SONA/ProjectSettings/TagManager.asset
Labels: :hammer_and_wrench:fix

#33 [Feat] 버튼 클릭 시 MissionBasketballScene으로 전환 기능 추가
  VR_SONA/Assets/Scenes/UIScene.unity
  VR_SONA/Assets/Scripts/UI/MissionSceneLoader.cs
  VR_SONA/Assets/Scripts/UI/MissionSceneLoader.cs.meta
  VR_SONA/ProjectSettings/EditorBuildSettings.asset
  VR_SONA/ProjectSettings/ProjectSettings.asset
Labels: :sparkles:feat

#34 [Fix] 타이머바와 코인 텍스트가 다른 오브젝트에 가려지던 문제 해결
  VR_SONA/Assets/Scenes/UIScene.unity
Labels: :hammer_and_wrench:fix

#35 feat: 농구 게임 Trigger 수정 및 타이머, 종료조건, 좌우 움직임 추가
  VR_SONA/Assets/Scenes/MissionBasketballScene.unity
  VR_SONA/Assets/Scripts/.DS_Store
  VR_SONA/Assets/Scripts/BasketBall/GameManager.cs
  VR_SONA/Assets/Scripts/BasketBall/GameManager.cs.meta
  VR_SONA/Assets/Scripts/BasketBall/GoalTrigger.cs
  VR_SONA/Assets/Scripts/BasketBall/HoopMovement.cs
  VR_SONA/Assets/Scripts/BasketBall/HoopMovement.cs.meta
  VR_SONA/Assets/Scripts/Timer.meta
  VR_SONA/Assets/Scripts/Timer/GameBasketballTimer.cs
  VR_SONA/Assets/Scripts/Timer/GameBasketballTimer.cs.meta
  VR_SONA/Assets/UI/Slider.prefab
  VR_SONA/Assets/UI/Slider.prefab.meta
  VR_SONA/ProjectSettings/TagManager.asset
Labels: :sparkles:feat

#36 [Feat] 미션 버튼 관련 로직 구현
  VR_SONA/Assets/Scenes/UIScene.unity
  VR_SONA/Assets/Scripts/UI/CoinUIManager.cs
  VR_SONA/Assets/Scripts/UI/MissionSceneLoader.cs
  VR_SONA/Assets/Scripts/UI/ShowBasketButtonOnCameraEnter.cs
  VR_SONA/Assets/Scripts/UI/ShowBasketButtonOnCameraEnter.cs.meta
  VR_SONA/ProjectSettings/TagManager.asset
Labels: :sparkles:feat

#37 [Feat] Additive 방식으로 미션 씬 로드 및 버튼/터레인 상태 제어 기능 추가
  VR_SONA/Assets/Scenes/MissionBasketballScene.unity
  VR_SONA/Assets/Scenes/UIScene.unity
  VR_SONA/Assets/Scripts/BasketBall/GameManager.cs
  VR_SONA/Assets/Scripts/UI/MissionSceneLoader.cs
  VR_SONA/Assets/Scripts/UI/ShowBasketButtonOnCameraEnter.cs
Labels: :sparkles:feat

#38 [Feat] 미션 수행 버튼 선택을 위한 문구 추가
  VR_SONA/Assets/Scenes/UIScene.unity
  VR_SONA/Assets/Scripts/UI/MissionSceneLoader.cs
  VR_SONA/Assets/Scripts/UI/ShowBasketButtonOnCameraEnter.cs
Labels: :sparkles:feat

#41 [Feat] DiceScene 로드 수정
  VR_SONA/Assets/Materials/Dice/Dice_plane.mat
  VR_SONA/Assets/Scenes/DiceScene.unity
  VR_SONA/Assets/Scenes/InteractionScene.unity
  VR_SONA/Assets/Scripts/VR/Dice/AutoCameraRender.cs
  VR_SONA/Assets/Scripts/VR/Dice/DiceManager.cs
  VR_SONA/Assets/Scripts/VR/Dice/DiceResultDetector.cs
  VR_SONA/Assets/Scripts/VR/Dice/DiceResultUI.cs
  VR_SONA/Assets/Scripts/VR/Dice/DiceSceneManager.cs
  VR_SONA/Assets/ThirdParty/AnimeNaturalEnvironment/Scripts/RenderTextureBaker.cs
Labels: :sparkles:feat

#45 [Feat] 플레이어 이동
  VR_SONA/Assets/Editor/RemoveObjects.cs
  VR_SONA/Assets/Materials/Dice Materail.physicMaterial
  VR_SONA/Assets/Materials/Dice Materail.physicMaterial.meta
  VR_SONA/Assets/Materials/DiceScene Material.physicMaterial
  VR_SONA/Assets/Materials/DiceScene Material.physicMaterial.meta
  VR_SONA/Assets/Materials/Tile Material.physicMaterial
  VR_SONA/Assets/Materials/Tile Material.physicMaterial.meta
  VR_SONA/Assets/Scenes/DiceScene.unity
  VR_SONA/Assets/Scenes/InteractionScene.unity
  VR_SONA/Assets/Scripts/Player/PlayerCanvas.cs
  VR_SONA/Assets/Scripts/Player/PlayerCanvas.cs.meta
  VR_SONA/Assets/Scripts/Player/PlayerManager.cs
  VR_SONA/Assets/Scripts/VR/Dice/DiceManager.cs
  VR_SONA/Assets/Scripts/VR/Dice/DiceResultDetector.cs
  VR_SONA/Assets/Scripts/VR/Dice/DiceResultUI.cs
  VR_SONA/Assets/Scripts/VR/Dice/DiceSceneManager.cs
  VR_SONA/Assets/Settings/High_PipelineAsset.asset
  VR_SONA/Assets/Settings/Low_PipelineAsset.asset
  VR_SONA/Assets/Settings/Medium_PipelineAsset.asset
  VR_SONA/Assets/Settings/Ultra_PipelineAsset.asset
  VR_SONA/Assets/Settings/Very High_PipelineAsset.asset
  VR_SONA/Assets/Settings/Very Low_PipelineAsset.asset
  VR_SONA/ProjectSettings/EditorBuildSettings.asset
  VR_SONA/ProjectSettings/ProjectSettings.asset
Labels: :sparkles:feat

#50 [Feat] 미션2 타이머 및 클리어 처리
  VR_SONA/Assets/Scenes/MissionWaterRushScene.unity
  VR_SONA/Assets/Scripts/WaterRush/WaterCollisionHandler.cs
  VR_SONA/Assets/Scripts/WaterRush/WaterCollisionHandler.cs.meta
  VR_SONA/Assets/Scripts/WaterRush/WaterJetShooter.cs
  VR_SONA/ProjectSettings/TagManager.asset
Labels: :sparkles:feat
