Repository Song-Daeun/VR_SONA, pull requests merged in 2025-06, with the labels that each got.

#55 [Fix] 워터러시 미션에서 결과 반영 안되던 문제 수정하여 건물 생성되도록 변경
  VR_SONA/Assets/Scenes/MissionWaterRushScene.unity
  VR_SONA/Assets/Scripts/WaterRush/WaterCollisionHandler.cs
  VR_SONA/Assets/Scripts/WaterRush/WaterJetShooter.cs
Labels: :hammer_and_wrench:fix

#68 [Fix] 농구씬에서 농구 발사 안되는 문제 해결, 농구공과 물줄기 destroy되도록 수정
  VR_SONA/Assets/Scenes/MissionBasketballScene.unity
  VR_SONA/Assets/Scripts/BasketBall/BasketballThrower.cs
  VR_SONA/Assets/Scripts/Core/MissionManager.cs
  VR_SONA/Assets/Scripts/WaterRush/WaterJetShooter.cs
Labels: :hammer_and_wrench:fix

#73 [Fix] 스펠북 도착 후 비행기 이벤트 발생 시 "주사위를 던져주세요" 버튼 안뜨도록 변경
  VR_SONA/Assets/Scripts/.DS_Store
  VR_SONA/Assets/Scripts/Core/GameManager.cs
  VR_SONA/Assets/Scripts/Core/SpellBookManager.cs
Labels: :bug:bug, :hammer_and_wrench:fix, :fire:hotfix

#74 [Fix] 스펠북 ui 및 종료 패널 관련 에러 해결
  VR_SONA/Assets/Scripts/Core/GameManager.cs
  VR_SONA/Assets/Scripts/Core/SpellBookManager.cs
Labels: :fire:hotfix

#75 [Fix] 마법서칸 두번째 이상 도착할 시 무조건 "이미 사용함!"이 뜨도록 해결
  VR_SONA/Assets/Scripts/Core/SpellBookManager.cs
Labels: :fire:hotfix
